fixed typo

diff --git a/DockerTest/Dockerfile b/DockerTest/Dockerfile
--- a/DockerTest/Dockerfile
+++ b/DockerTest/Dockerfile
@@ -18,7 +18,7 @@ RUN dotnet test --logger "trx;LogFileName=TestResult.trx"; \
 	echo $? > /testresult/passorfail
 
 FROM test AS publish
-RUN testresult=$(cat /testresult/passorfail);if [ 0 -eq $testresult ]; then echo "Test passed, continuing" >&2; else echo "Tests failed, aborting build" >&2; exit 1 >&2; fi
+RUN testresult=$(cat /testresult/passorfail);if [ 0 -eq $testresult ]; then echo "Tests passed, continuing" >&2; else echo "Tests failed, aborting build" >&2; exit 1 >&2; fi
 WORKDIR /src/DockerTest
 RUN dotnet publish DockerTest.csproj -c Release -o /app
 
