Added running tests

diff --git a/DockerTest/Dockerfile b/DockerTest/Dockerfile
--- a/DockerTest/Dockerfile
+++ b/DockerTest/Dockerfile
@@ -11,7 +11,15 @@ COPY . .
 WORKDIR /src/DockerTest
 RUN dotnet build DockerTest.csproj -c Release -o /app
 
-FROM build AS publish
+FROM build as test
+WORKDIR /src
+RUN mkdir /testresult
+RUN dotnet test --logger "trx;LogFileName=TestResult.trx"; \
+	echo $? > /testresult/passorfail
+
+FROM test AS publish
+RUN testresult=$(cat /testresult/passorfail);if [ 0 -eq $testresult ]; then echo "Test passed, continuing" >&2; else echo "Tests failed, aborting build" >&2; exit 1 >&2; fi
+WORKDIR /src/DockerTest
 RUN dotnet publish DockerTest.csproj -c Release -o /app
 
 FROM base AS final
